# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170509_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
