# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170509_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='avatars/'),
        ),
    ]
